// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf2q--pPJOKGwTJTkFi_E5s1xXLFz3leY',
    appId: '1:236639645734:web:78edb8844ea8e54025f6e7',
    messagingSenderId: '236639645734',
    projectId: 'flutterapp-1a535',
    authDomain: 'flutterapp-1a535.firebaseapp.com',
    storageBucket: 'flutterapp-1a535.appspot.com',
    measurementId: 'G-W1BBLR7ME5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOfzwj57aGIygyIBZ4wMwnugRn2d4El1Y',
    appId: '1:236639645734:android:d19ed6c589b5d0e425f6e7',
    messagingSenderId: '236639645734',
    projectId: 'flutterapp-1a535',
    storageBucket: 'flutterapp-1a535.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0KjWPQ-No2EKDGbf9crCCe7zDlVd_ivc',
    appId: '1:236639645734:ios:694c70863544a5be25f6e7',
    messagingSenderId: '236639645734',
    projectId: 'flutterapp-1a535',
    storageBucket: 'flutterapp-1a535.appspot.com',
    iosClientId: '236639645734-bis8fbbdm8fqv1fsq9kc12vk4huegraf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNoiteBanco',
  );
}
